import { ArrowRight, Zap, ShieldCheck, Truck, Smartphone, Headphones, BatteryCharging, Laptop, Gamepad2, Watch, Package } from 'lucide-react';
import { site } from '../config/site';
import ProductCard from '../components/ProductCard';
const splitTitle = lines => <>{lines[0]}<br/><i>{lines[1]}</i></>;
const categoryIcons = { Phones: Smartphone, Audio: Headphones, Power: BatteryCharging, Computing: Laptop, Gaming: Gamepad2, Accessories: Watch };
export default function Home({ go, open, add, cartQty, wishlist, toggleWishlist, products }) {
  const hero=products[0], story=products[1]||hero;
  return <>
    <section className="tech-hero"><div className="tech-hero-copy"><div className="hero-kicker"><span /> {site.copy.heroEyebrow}</div><h1>{splitTitle(site.copy.heroTitle)}</h1><p className="lead">{site.copy.description}</p><div className="hero-actions"><button className="primary" onClick={() => go('shop')}>{site.labels.shopNow} <ArrowRight /></button><button className="hero-link" onClick={() => go('shop')}>See what’s new</button></div><div className="hero-points"><span><Zap /> Everyday essentials</span><span><ShieldCheck /> Carefully selected</span></div></div>
      <div className="tech-hero-visual"><div className="hero-orb orb-blue"/><div className="hero-orb orb-pink"/><div className="hero-orb orb-lime"/>{hero&&<img src={hero.images?.[0]} alt={hero.name} width="800" height="1000" fetchPriority="high"/>}<div className="hero-sticker"><strong>Life</strong><span>with ease.</span></div></div></section>
    <section className="brand-strip"><span>SMARTER EVERYDAY</span><span>POWER</span><span>AUDIO</span><span>COMPUTING</span><span>GAMING</span><span>ACCESSORIES</span></section>
    <section className="home-categories"><div className="section-head"><div><p className="eyebrow">SHOP BY CATEGORY</p><h2>Find your kind of tech.</h2></div><button onClick={() => go('shop')}>All products <ArrowRight /></button></div><div className="category-box-grid">{[...new Set(products.map(product => product.category).filter(Boolean))].map(category => { const Icon = categoryIcons[category] || Package; const sample = products.find(product => product.category === category); return <button className="home-category-box" key={category} onClick={() => go('shop', category)}><span className="home-category-icon"><Icon aria-hidden="true" /></span><span className="home-category-label">{category}</span>{sample?.images?.[0] && <img src={sample.images[0]} alt="" loading="lazy" />}<ArrowRight className="home-category-arrow" aria-hidden="true" /></button>; })}</div></section>
    <section className="store-intro"><p className="eyebrow">{site.copy.introEyebrow}</p><h2>{splitTitle(site.copy.introTitle)}</h2><p>{site.copy.introText}</p><div className="intro-benefits"><span><Truck/> Easy ordering</span><span><Zap/> Useful tech</span><span><ShieldCheck/> Straightforward shopping</span></div></section>
    <section className="store-featured"><div className="section-head"><div><p className="eyebrow">{site.copy.featuredEyebrow}</p><h2>{site.copy.featuredTitle}</h2></div><button onClick={() => go('shop')}>{site.labels.viewAll} <ArrowRight/></button></div><div className="product-grid">{products.slice(0,3).map(product=><ProductCard key={product.id} product={product} open={open} add={add} quantity={cartQty(product)} wishlist={wishlist} toggleWishlist={toggleWishlist}/>)}</div></section>
    <section className="tech-story">{story&&<><div className="story-visual"><img src={story.images?.[0]} alt={story.name} width="800" height="1000" loading="lazy"/><span>AWESOME / 02</span></div><div className="tech-story-copy"><p className="eyebrow">{site.copy.storyEyebrow}</p><h2>{splitTitle(site.copy.storyTitle)}</h2><p>{site.copy.storyText}</p><button className="secondary" onClick={() => go('about')}>Our story <ArrowRight/></button></div></>}</section>
    <section className="store-cta"><p className="eyebrow">{site.copy.ctaEyebrow}</p><h2>{splitTitle(site.copy.ctaTitle)}</h2><button className="primary" onClick={() => go('shop')}>{site.labels.shopCollection} <ArrowRight/></button></section>
  </>;
}